# Generated by Django 2.1.7 on 2019-03-08 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=40)),
                ('owner_id', models.IntegerField(max_length=11)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental_price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'въпроси',
            },
        ),
    ]
