# Generated by Django 2.1.7 on 2019-03-08 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'verbose_name_plural': 'лодки'},
        ),
        migrations.AlterField(
            model_name='boat',
            name='date_made',
            field=models.DateTimeField(default=datetime.date(2019, 3, 8)),
        ),
    ]
