# Generated by Django 2.1.7 on 2019-03-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_auto_20190308_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='date_made',
        ),
    ]
