# Generated by Django 2.1.7 on 2019-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_remove_boat_date_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='d',
        ),
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
