# Generated by Django 2.1.7 on 2019-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_auto_20190308_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
