# Generated by Django 2.1.7 on 2019-03-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_auto_20190308_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
