# Generated by Django 2.1.7 on 2019-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_auto_20190308_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
