# Generated by Django 2.1.7 on 2019-03-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_auto_20190309_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='owner_id',
            field=models.IntegerField(),
        ),
    ]
