# Generated by Django 2.1.3 on 2018-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181112_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(default='', max_length=100),
        ),
    ]
