# Generated by Django 2.1.3 on 2018-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181112_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='d',
            new_name='D',
        ),
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.CharField(choices=[(models.CharField(default='', max_length=100), 'A'), (models.CharField(default='', max_length=100), 'B'), (models.CharField(default='', max_length=100), 'C'), (models.CharField(default='', max_length=100), 'D')], default=models.CharField(default='', max_length=100), max_length=2),
        ),
    ]
