# Generated by Django 2.1.3 on 2018-11-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181112_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='right_answer',
        ),
    ]
