# Generated by Django 2.1.3 on 2018-11-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20181112_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'отговори'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'въпроси'},
        ),
    ]
