# Generated by Django 2.1.7 on 2019-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=40)),
                ('disp_name', models.CharField(max_length=40)),
                ('provid_name', models.CharField(max_length=40)),
                ('firm_name', models.CharField(max_length=40)),
                ('turbine_type', models.CharField(max_length=40)),
                ('control_type', models.CharField(max_length=10)),
                ('supported_by', models.CharField(max_length=20)),
                ('number_of_turbines', models.IntegerField(max_length=11)),
                ('turbine_power', models.FloatField()),
                ('turbine_id', models.CharField(max_length=20)),
                ('output_name', models.CharField(max_length=30)),
                ('station_name', models.CharField(max_length=20)),
                ('gru_name', models.CharField(max_length=25)),
                ('wind_plant', models.CharField(max_length=20)),
                ('percent', models.CharField(max_length=10)),
                ('epro_provid', models.CharField(max_length=4)),
                ('sot_firm', models.CharField(max_length=20)),
                ('sot_name', models.CharField(max_length=10)),
                ('forecaster', models.CharField(max_length=20)),
                ('forecast_type', models.CharField(max_length=20)),
                ('isp_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'турбини',
            },
        ),
    ]
