# Generated by Django 2.1.7 on 2019-03-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbines', '0002_auto_20190309_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbine',
            name='supported_by',
        ),
    ]
